modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"

# License
license="GNU GPLv3"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/gottsch/gottsch-minecraft-Monster-Manual/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="gottsch's Monster Manual" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
updateJSONURL="https://raw.githubusercontent.com/gottsch/gottsch-minecraft-Monster-Manual/1.20.1-main/update.json"

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/gottschs-monster-manual" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="monster_manual_mod_logo.png" #optional

# A text field displayed in the mod UI
credits="" #optional

# A text field displayed in the mod UI
authors="gottsch" #optional

# The description text for the mod (multi line!) (#mandatory)
description="A mod that adds a classical set of mobs to your Minecraft world. The main influence of most of these creatures is from playing Ultima IV & V back in the day."

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.gmm]] #optional
# the modid of the dependency
modId="forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="${forge_version_range}" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"
# Here's another dependency
[[dependencies.gmm]]
modId="minecraft"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.gmm]]
modId="gottschcore"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[2.6.0,]"
# gmm builds on gottschcore, so gottschcore must load first -> gmm loads AFTER it
ordering="AFTER"
side="BOTH"